Repository andela/octopus-bn-frontend, pull requests merged in 2020-04, with the labels that each got.

#1 #170947368 Setup an empty react project
  .babelrc
  .eslintrc.json
  .gitignore
  README.md
  package-lock.json
  package.json
  public/index.html
  src/App.js
  src/index.js
  src/theme.js
  webpack.config.js
Labels: read for review

#2 #170947370 Setup testing environment
  .gitignore
  jest.config.js
  package-lock.json
  package.json
  src/App.js
  src/__tests__/__snapshots__/index.spec.js.snap
  src/__tests__/index.spec.js
Labels: Ready for Peer Review

#4 #170947373 Setup SASS processing on the client
  package-lock.json
  package.json
  src/App.js
  src/__tests__/__snapshots__/index.spec.js.snap
  src/styles/styles.scss
  src/styles/variables.scss
  webpack.config.js
Labels: Ready for TTL Review

#3 #170947371 #170947375 setup travis CI and codeClimate
  .coveralls.yml
  .gitignore
  .travis.yml
  README.md
  jest.config.js
  package-lock.json
  package.json
Labels: Ready for Peer Review

#7 #170947376 Update the readme
  README.md
Labels: Ready for TTL Review

#6 #170947377 Configure storybook
  .storybook/main.js
  package-lock.json
  package.json
  src/stories/App.stories.js
Labels: Ready for TTL Review

#5 #170947369 - Redux Set-Up
  .coveralls.yml
  package-lock.json
  package.json
  src/App.js
  src/__tests__/__snapshots__/index.spec.js.snap
  src/__tests__/counterActionCreator.spec.js
  src/__tests__/counterReducer.spec.js
  src/components/Counter.js
  src/redux/actions/index.js
  src/redux/reducers/counter.js
  src/redux/reducers/index.js
  src/redux/store.js
  webpack.config.js
Labels: Ready for TTL Review

#8 #170947372 React Router
  .coveralls.yml
  .travis.yml
  package-lock.json
  package.json
  src/App.js
  src/__tests__/__snapshots__/index.spec.js.snap
  src/components/index.js
  src/views/index.js
Labels: Ready for TTL Review
